application:
  # dev开发环境 test测试环境 prod线上环境
  mode: dev
  # 服务器ip，默认使用
  host: http://127.0.0.1:8080
  # 端口号
  port: 8080
  # jwt 密钥
  signingKey: KYYbng4o9I1jJFqOC6wL9JL9vjt7
  # jwt 过期时间 单位：分钟
  tokenTimeout: 1440
  #id混淆
  idConfusion: 123456
  i18: zh-CN
  #卡密生成密钥
  redeemKey: 123456
  # 文件域名
  fileHost: http://127.0.0.1:8080
postgresql:
    host: 127.0.0.1
    port: 5432
    user: root
    password: 123456
    database: kk_bbs
    sslmode: disable
redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    poolSize: 50
    minIdleConns: 10
    maxConnAge: 5
    poolTimeout: 30
    idleTimeout: 5
    idleCheckFrequency: 60
# 邮件服务器配置，用于邮件通知
smtp:
  host: us2.smtp.mailhostbox.com
  port: 587
  username: admin@hxsj.in
  password: fmzqUps2